apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: default
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: 192.168.5.182:5000/producer:latest
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "image_data"
            - name: ENVIRONMENT
              value: "production"  # Any additional environment variables as needed
