# Use an official Python image as the base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the local files into the container
COPY . /app

# Create a virtual environment
RUN python3 -m venv /app/venv

# Activate the virtual environment and install dependencies
RUN . /app/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install uv && \
    uv pip install kafka-python pycocotools pandas matplotlib numpy

# Set the command to run the scheduler.py script directly
CMD ["/app/venv/bin/python", "scheduler.py"]
