apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: default
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: 192.168.5.182:5000/scheduler:latest
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: KAFKA_IMAGE_TOPIC
              value: "image_data"
            - name: KAFKA_VLM_TOPIC
              value: "vlm_data"
            - name: NUM_CHANNELS
              value: "4"
            - name: ENVIRONMENT
              value: "production"  # Any additional environment variables as needed
